#!/bin/bash

use_rclone="True" # Set to True to use rclone to copy the backup to a cloud storage provider. You must install and setup rclone for this to work.
rclone_remote="google_drive" # The name of the rclone remote to use
backup_path="/home/mcserver/minecraft/backup"
script_start_time=$(date +"%Y-%m-%d %H:%M:%S")

cp \
 /home/mcserver/minecraft/backup/minecraft_day3.tar.gz \
 /home/mcserver/minecraft/backup/minecraft_15th.tar.gz

if [[ "$use_rclone" == "True" ]]; then
    rclone copy "${backup_path}/minecraft_15th.tar.gz" "${rclone_remote}:"
    echo "Fifteenth of month backup run from $script_start_time to $(date +"%Y-%m-%d %H:%M:%S %Z")" >> "${backup_path}/backup_log.txt"
    rclone copy "${backup_path}/backup_log.txt" "${rclone_remote}:"
fi