#!/bin/bash

use_rclone="True" # Set to True to use rclone to copy the backup to a cloud storage provider. You must install and setup rclone for this to work.
script_start_time=$(date +"%Y-%m-%d %H:%M:%S")

cp \
 /home/mcserver/minecraft/backup/minecraft_day4.tar.gz \
 /home/mcserver/minecraft/backup/minecraft_1st.tar.gz

if [[ "$use_rclone" == "True" ]]; then
    rclone copy /home/mcserver/minecraft/backup/minecraft_1st.tar.gz "${rclone_remote}:"
    echo "First of month backup run from $script_start_time to $(date +"%Y-%m-%d %H:%M:%S %Z")" >> /home/mcserver/minecraft/backup/backup_log.txt
    rclone copy /home/mcserver/minecraft/backup/backup_log.txt "${rclone_remote}:"
fi