## preferences
PREFS:
  NUM_DAYS: 5
  MINIMUM_PLAYS: 30
  USE_RCLONE: True

## consants
CONSTANTS:
  RCLONE_REMOTE: google_drive
  MINECRAFT_PATH: /home/mcserver/minecraft
  BACKUP_PATH: /home/mcserver/minecraft/backup
  LOG_PATH: /home/mcserver/minecraft/logs
  TEMP_LOG_PATH: /home/mcserver/minecraft/temp_logs